### ISSUE TITLE
Create Contributing.MD

### ISSUE THREAD

**Issue by ShaileshSurya** [ShaileshSurya/hammer#11]

**Comment by ShaileshSurya** [comment]
Link #5

**Comment by wenderzxavier** [comment]
I would like to work on this! :D

**Comment by ShaileshSurya** [comment]
That will be great @wenderzxavier. Make sure that we will be using a fork and pull request workflow.

**Comment by wenderzxavier** [comment]
#13

**Comment by ShaileshSurya** [comment]
@wenderzxavier  Thank you for submitting the PR. The wording is lucid. Great work there.
