### ISSUE TITLE
Add Examples for library use. 

### ISSUE THREAD

**Issue by ShaileshSurya** [ShaileshSurya/hammer#12]

**Comment by ShaileshSurya** [comment]
Link #10

**Comment by ShaileshSurya** [comment]
@ZachPlunkett Can you add the details on this issue. It will help us with the tracking.

**Comment by ZachPlunkett** [comment]
Add an example for a user to easily see how hammer is used in a program. 

For now the examples should include

- Execute()
- ExecuteInto()
