### ISSUE TITLE
Support for PostForm() http method. 

### ISSUE THREAD

**Issue by ShaileshSurya** [ShaileshSurya/hammer#2]
We need to add support for https://golang.org/pkg/net/http/#Client.PostForm

**Comment by Xk0nSid** [comment]
@ShaileshSurya I would like to work on this.

**Comment by ShaileshSurya** [comment]
@Xk0nSid That will be great. Please go ahead. 

I will suggest following API's for the change. 

```
client := hammer.New()
request, err := hammer.RequestBuilder().
		PostForm().
		WithURL("http://localhost:8081/employee").
                WithFormValues("key","Value").
                WithFormValues("key","Value").
		Build()
```

**Comment by ShaileshSurya** [comment]
@Xk0nSid Feel free to assign yourself this issue if you are actively working on this.
