### ISSUE TITLE
Code Refactoring : Replace Requesto With Hammer. 

### ISSUE THREAD

**Issue by ShaileshSurya** [ShaileshSurya/hammer#4]
As a part of renaming the repository from Requesto to Hammer. We may not have refactored the repository code well. 

Places to check. 
1. Filenames 
2. Variable names. 
3. tests. 
4. documentation.

**Comment by andyyaldoo** [comment]
@ShaileshSurya I would like to take this, could you assign me the issue? Will open a PR on Saturday. If no PR by Sunday, feel free to unassign

**Comment by ShaileshSurya** [comment]
Yes @andyyaldoo  feel free to open a PR.
